### ISSUE TITLE
transport: better tag allocation algorithm

### ISSUE THREAD

**Issue by stevvooe** [docker/go-p9p#5]
The current tag allocation algorithm is "hope++". We need to handle collisions against outstanding requests, rollover and exhaustion.

**Comment by joushou** [comment]
It must also avoid NOTAG for non-Tversion requests.

**Comment by joushou** [comment]
From #2

> This is good to know. During implementation I wasn't sure how long session lifetimes would be.

It of course differs between use cases, but I'm assuming that you're not terminating your server after a few minutes. If you only read a file per minute, then it's of course going to take a while to run around.

> We are actually handling Tflush within the transport and server, automatically. Clients can cancel an operation through the context and the flush is handled automatically. There are some details that are nasty to get right for flush handling and we thought it would be better to hide these in the implementation.

Ah, okay. I noticed the context, but didn't get the... context (hahah... hah... sorry). I kept my transport "dumb" (It can send a message and return a response, and you can tell it to stop waiting for a response on a tag), and made that the responsibility of the high-level client. I haven't actually added cancellation for individual requests in the high-level client yet, as I don't know how to do it cleanly... The context is the now the status quo, and might end up being my solution, but it always left a funky taste in my mind. Never found out why, though.

# Tags!

Anyway, a few things to note about the tag handling that must be considered during tag allocation:

1. Tversion must not use a tag, which is signified by NOTAG (0xFFFF). All other requests must bear a tag. The transport will have to type assert the message to select the tag (another reason I only supply a tag pool to the higher level client, rather than selecting things at the transport layer). Right now, you just start at 0 it seems (meaning the Tversion you send will be invalid, unless it is the 65536th message), and the last message before tags roll around is going to be invalid (unless it happened to be a Tversion). Some servers will enforce this, some will not. My own fileserver sends an Rerror if Tversion does not use NOTAG, but does not otherwise consider it magic and allows other requests to use it.
2. A request is not cancelled before you receive the Rflush. A server may send the response to the flushed request before responding with an Rflush. In this case, the client should handle the response despite having sent a Tflush, as it might have had consequences on some server state, including the state of your currently available fids. When cancelling the context, you would therefore have to wait for an extra roundtrip (that can time out due to broken server/network issues), and a response may still be returned after having cancelled the context, which might be a bit against how contexts are "supposed" to work.
3. If you send multiple Tflushes on 1 tag, they must be processed in order, and the server is only required to answer the last one if it's lazy, meaning that the client must handle the earlier Tflushes as being implicitly flushed. I suggest just not triggering this behaviour by never sending more than 1 Tflush on a tag; that was my approach to the problem, at least. (As for a server, just don't handle Tflush requests out of order.)
4. Don't trample on existing tags.

That's all I could think of for now.

**Comment by stevvooe** [comment]
Thanks for the description. This will really help in implementing this.

I am not sure about your interest, but do you want to take a crack at a PR? I'm not going to be able to get to this bug in a timely manner (although your feedback is going to drastically cut down on my wandering through 9p docs).

>  I kept my transport "dumb" (It can send a message and return a response, and you can tell it to stop waiting for a response on a tag), and made that the responsibility of the high-level client.

Indeed. The design of this package was really focused around exposing the innards of 9p without getting the full `Fcall` experience. At some point, I'd like to rearrange `Channel`, `transport`, the negotiation methods and even support arbitrary message types to make lower-level applications possible, in addition to replacing codecs. We just haven't needed it yet.

**Comment by joushou** [comment]
#15 avoids tag collisions and such.

**Comment by stevvooe** [comment]
Closed by #15.
